title: My first attempt at a webpage/blog!
author: GitHub User
email: rebecca.lee@hotmail.fr
description: My new Site will tell you about the different websites I enjoy browsing and why.
  

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
